---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-6.6
  run_list: recipe[yum]
- name: centos-7.0
  run_list: recipe[yum]
- name: ubuntu-14.10
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-13.10
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: debian-7.7
  run_list: recipe[apt]

suites:
- name: nrsysmond-default
  run_list:
  - recipe[minitest-handler]
  - recipe[newrelic-ng::nrsysmond-default]
  attributes:
    newrelic-ng:
      license_key: TESTKEY_NRSYSMOND

- name: plugin-agent-default
  run_list:
  - recipe[minitest-handler]
  - recipe[newrelic-ng::plugin-agent-default]
  attributes:
    newrelic-ng:
      license_key: TESTKEY_PLUGIN_AGENT
      plugin-agent:
        service_config: >
          postgresql:
            host: localhost
            port: 5432
            dbname: postgres
            user: newrelic

- name: generic-agent-default
  run_list:
  - recipe[ruby::1.9.1]
  - recipe[minitest-handler]
  - recipe[newrelic-ng::generic-agent-default]
  attributes:
    newrelic-ng:
      license_key: TESTKEY_GENERIC_AGENT
      generic-agent:
        agents:
          sidekiq_status_agent:
            source: https://github.com/eksoverzero/newrelic_sidekiq_agent/archive/V2.0.tar.gz
            config: >
              - instance_name: sidekiq_agent_test
                uri: redis://localhost:6379
                namespace: namespace

- name: php-agent-default
  run_list:
  - recipe[minitest-handler]
  - recipe[apache2]
  - recipe[newrelic-ng::php-agent-default]
  attributes:
    apache:
      default_modules:
      - status
      - alias
      - auth_basic
      - authn_file
      - authz_groupfile
      - authz_host
      - authz_user
      - dir
      - env
      - mime
      - setenvif
      - deflate
      - expires
      - headers
      - log_config
      - logio
      - php5
    newrelic-ng:
      license_key: TESTKEY_PHP_AGENT
