LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

MethodLength:
  Max: 50

AbcSize:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

Documentation:
  Enabled: false

TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

# Ignore snake_case filename warnings for now
Style/FileName:
  Enabled: false
